# Generated by Django 3.1 on 2021-11-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField(unique=True)),
                ('cbu', models.DecimalField(decimal_places=0, max_digits=22, unique=True)),
                ('alias', models.CharField(max_length=25, unique=True)),
                ('banco_emisor', models.CharField(choices=[], max_length=20)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'ordering': ('persona',),
            },
        ),
    ]
