# Generated by Django 3.1 on 2021-11-10 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_cuentabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='alias',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
